### ISSUE TITLE
Don't overwrite default styling for Bootstrap popovers

### ISSUE THREAD

**Issue by DanielApt** [easelinc/tourist#32]
Currently [tourist.css](https://github.com/easelinc/tourist/blob/master/tourist.css) is overwriting the default styling of bootstrap popovers. 

This breaks the design of the popovers which are used *without tourist*. Especially the [line which removes the default padding](https://github.com/easelinc/tourist/blob/master/tourist.css#L12) is causing issues, as it's non-specific.

Instead I propose that the popovers generated by tourist should be created with a `tourist-popover` class, and all styling should be applied to only these popovers.

**Comment by benogle** [comment]
Fixed in #33
