### ISSUE TITLE
CloseButton does not work

### ISSUE THREAD

**Issue by olman21** [easelinc/tourist#36]
I set the value for closeButton = true in all of my steps, but the close button doesn't show, and the user can't close the turorial until the end, Am I wrong with something?

![2015-08-12_1414](https://cloud.githubusercontent.com/assets/1875360/9235505/5cd7fcd2-40fc-11e5-9b4a-b8fd59a6cbdc.png)

**Comment by tommrr** [comment]
Did you find a solution to this problem? I have the same issue right now.
